# Generated by Django 4.1.1 on 2023-03-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_student_teacher_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('places', models.CharField(max_length=3)),
                ('price', models.FloatField()),
                ('terms', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='engine.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.teacher')),
            ],
        ),
    ]
